server:
  port: 8080

spring:
  application:
    name: api-consumer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: banks
          uri: http://localhost:8090
          predicates:
            - Path=/api/banks/**
        - id: accounts
          uri: http://localhost:9090
          predicates:
            - Path=/api/accounts/**

eureka:
  client:
    register-with-eureka: false
