server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-consumer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origin-patterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600
      routes:
        - id: banks
          uri: http://ms-banks:8090
          predicates:
            - Path=/api/banks/**
        - id: accounts
          uri: http://ms-accounts:9090
          predicates:
            - Path=/api/accounts/**

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://ms-eureka:8761/eureka/}
