server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-consumer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: banks
          uri: http://ms-banks:8090
          predicates:
            - Path=/api/banks/**
        - id: accounts
          uri: http://ms-accounts:9090
          predicates:
            - Path=/api/accounts/**

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/
