server:
  port: 8080

spring:
  application:
    name: api-consumer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600
      routes:
        - id: banks
          uri: http://localhost:8090
          predicates:
            - Path=/api/banks/**
        - id: accounts
          uri: http://localhost:9090
          predicates:
            - Path=/api/accounts/**

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
