server:
  port: 9090

spring:
  application:
    name: ms-accounts

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ms_accounts_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    ms-banks:
      url: http://localhost:8090