server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: ms-accounts

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-accounts:5432/ms_accounts_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    open-in-view: false

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:ms-accounts}
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://ms-eureka:8761/eureka/}
