server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: ms-banks

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-banks:5432/ms_banks_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    open-in-view: false

eureka:
  instance:
    hostname: ${EUREKA_BANKS_INSTANCE_HOSTNAME:ms-banks}
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://ms-eureka:8761/eureka/}

feign:
  client:
    ms-accounts:
      url: ${FEIGN_MS_ACCOUNTS_URL:http://ms-accounts:9090}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
