server:
  port: 8090

spring:
  application:
    name: ms-banks

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ms_banks_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
