server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: ms-eureka

eureka:
  instance:
    hostname: ms-eureka
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/
